# ros_gz_bridge.yaml
# Gazebo -> ROS sensor mappings

- ros_topic_name: "/uav1/scan"
  gz_topic_name: "/world/aerostack_world/model/aerostack_drone/link/base_link/sensor/lidar/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
  publisher_qos:
    reliability: "best_effort"
    durability: "volatile"

- ros_topic_name: "/uav1/camera/image_raw"
  gz_topic_name: "/world/aerostack_world/model/aerostack_drone/link/base_link/sensor/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  publisher_qos:
    reliability: "best_effort"
    durability: "volatile"

- ros_topic_name: "/uav1/camera/camera_info"
  gz_topic_name: "/world/aerostack_world/model/aerostack_drone/link/base_link/sensor/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/uav1/range"
  gz_topic_name: "/world/aerostack_world/model/aerostack_drone/link/base_link/sensor/rangefinder/scan"
  ros_type_name: "sensor_msgs/msg/Range"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
